### ISSUE TITLE
Sai lỗi trả về khi xóa nhà không tồn tại 

### ISSUE THREAD

**Issue by kztera** [tridevi-team/renthub-backend#52] opened 2024-10-26 10:59 UTC
Kết quả hiện tại

![image](https://github.com/user-attachments/assets/d71cb8b9-a558-4d13-b4d7-8a4e8ae2ee69)
![image](https://github.com/user-attachments/assets/4c2a41d6-5c8f-49cf-8245-d7f0d6e44307)

Kết quả mong đợi:

```json
{
  "success": false,
  "code": "HOUSE_NOT_FOUND",
  "message": "House not found"
}
```

**Comment by tmquang0209** [comment] 2024-10-26 11:08
I think the problem is authorization, the delete home message is correct. I will check again and reply later
![image](https://github.com/user-attachments/assets/aa8b862f-fbcf-4759-a1d1-fb6e8e755cda)

**Comment by tmquang0209** [comment] 2024-10-26 11:30
I'm committed to fixing this issue, please check back and close the issue if it works
[Here](https://github.com/tridevi-team/renthub-backend/commit/177895c4eae1078547efdfc6220de9bd3c2cdff6)

**Closed** 2024-12-01 07:17 UTC
Labels: bug
